//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algorithms_CSharp_Course.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Algorithms_CSharp_Course.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 528
        ///167
        ///-968
        ///537
        ///832
        ///-136
        ///989
        ///-409
        ///-202
        ///44
        ///-259
        ///-799
        ///-821
        ///-579
        ///132
        ///982
        ///700
        ///577
        ///422
        ///824
        ///697
        ///-686
        ///-156
        ///355
        ///-429
        ///135
        ///-170
        ///389
        ///-422
        ///67
        ///-497
        ///987
        ///995
        ///557
        ///-370
        ///-447
        ///298
        ///-738
        ///-918
        ///592
        ///272
        ///217
        ///470
        ///692
        ///146
        ///461
        ///531
        ///760
        ///-871
        ///468
        ///20
        ///220
        ///-990
        ///440
        ///-938
        ///213
        ///-677
        ///-324
        ///-35
        ///-304
        ///-966
        ///-401
        ///-987
        ///731
        ///-460
        ///-246
        ///-794
        ///-378
        ///791
        ///-421
        ///-317
        ///437
        ///495
        ///830
        ///-449
        ///-520
        ///-157
        ///151
        ///-792
        ///110
        ///604
        ///69
        ///259
        ///109
        ///-953
        ///283
        ///976
        ///-445
        ///495
        ///416
        ///-770
        ///-379
        ///297
        ///385
        ///558
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _16Kints {
            get {
                return ResourceManager.GetString("_16Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723
        ///  52921
        /// 600291
        /// 799037
        /// 836049
        ///-190454
        ///  13962
        ///-714343
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1Kints {
            get {
                return ResourceManager.GetString("_1Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723
        ///  52921
        /// 600291
        /// 799037
        /// 836049
        ///-190454
        ///  13962
        ///-714343
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2Kints {
            get {
                return ResourceManager.GetString("_2Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723
        ///  52921
        /// 600291
        /// 799037
        /// 836049
        ///-190454
        ///  13962
        ///-714343
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4Kints {
            get {
                return ResourceManager.GetString("_4Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  324110
        ///-442472
        /// 626686
        ///-157678
        /// 508681
        /// 123414
        /// -77867
        /// 155091
        /// 129801
        /// 287381
        /// 604242
        /// 686904
        ///-247109
        ///  77867
        /// 982455
        ///-210707
        ///-922943
        ///-738817
        ///  85168
        /// 855430
        ///-365580
        ///-174307
        /// -28560
        /// 888769
        ///-887534
        ///-563503
        /// 752524
        /// 777031
        /// 385644
        ///-768774
        /// 211244
        /// 792814
        ///-475905
        /// 968127
        ///-504909
        /// 570656
        ///-458444
        ///-957331
        /// 259322
        ///-648617
        /// 451074
        /// 858015
        /// 849248
        ///-361918
        ///-683640
        ///-449851
        ///-363749
        ///-425926
        /// 418216
        ///-609284
        /// 460009
        /// 331758
        ///-600376
        /// 325398
        /// 279751
        /// 592222
        /// 309723
        ///  52921
        /// 600291
        /// 799037
        /// 836049
        ///-190454
        ///  13962
        ///-714343
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8Kints {
            get {
                return ResourceManager.GetString("_8Kints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rebel statement sent to Lisbon from Jamba said 86 government soldiers and 13 guerrillas were killed in the fighting that ended Jan. 3. It said the rebel forces sill held Mavinga.
        ///Authorities last week issued a vacate order for a club in Manhattan and closed another in the Bronx.
        ///At the first Pan Am bankruptcy hearing, for example, at least five airlines were represented.
        ///Mr. Neigum, poker-faced during the difficult task, manages a 46-second showing.
        ///This, combined with the container division talks, sugges [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leipzig100k {
            get {
                return ResourceManager.GetString("leipzig100k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rebel statement sent to Lisbon from Jamba said 86 government soldiers and 13 guerrillas were killed in the fighting that ended Jan. 3. It said the rebel forces sill held Mavinga.
        ///Authorities last week issued a vacate order for a club in Manhattan and closed another in the Bronx.
        ///At the first Pan Am bankruptcy hearing, for example, at least five airlines were represented.
        ///Mr. Neigum, poker-faced during the difficult task, manages a 46-second showing.
        ///This, combined with the container division talks, sugges [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string leipzig300k {
            get {
                return ResourceManager.GetString("leipzig300k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project Gutenberg EBook of A Tale of Two Cities, by Charles Dickens
        ///
        ///This eBook is for the use of anyone anywhere at no cost and with
        ///almost no restrictions whatsoever.  You may copy it, give it away or
        ///re-use it under the terms of the Project Gutenberg License included
        ///with this eBook or online at www.gutenberg.net
        ///
        ///
        ///Title: A Tale of Two Cities
        ///       A story of the French Revolution
        ///
        ///Author: Charles Dickens
        ///
        ///Release Date: September 25, 2004 [EBook #98]
        ///
        ///Language: English
        ///
        ///Character se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tale {
            get {
                return ResourceManager.GetString("tale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it was the best of times it was the worst of times
        ///it was the age of wisdom it was the age of foolishness
        ///it was the epoch of belief it was the epoch of incredulity
        ///it was the season of light it was the season of darkness
        ///it was the spring of hope it was the winter of despair.
        /// </summary>
        internal static string tinyTale {
            get {
                return ResourceManager.GetString("tinyTale", resourceCulture);
            }
        }
    }
}
